# .github/workflows/ci.yml
name: CI for Recipes App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or your preferred Node.js version

      - name: Install wait-on (for service readiness)
        run: npm install -g wait-on # Install globally for easy access

      - name: Install Backend Dependencies
        run: npm install
        working-directory: ./recipes-api

      - name: Install Frontend Dependencies
        run: npm install
        working-directory: ./app-recipes-nicaraguan

      - name: Install Playwright Test Dependencies
        run: npm install
        working-directory: ./recipes-suite-automation

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./recipes-suite-automation

      - name: Start Backend
        run: node backend.js &
        working-directory: ./recipes-api
        # Wait for backend to be ready on port 5000
      - name: Wait for Backend
        run: wait-on http://localhost:5000/api/recipes

      - name: Start Frontend
        run: npm start &
        working-directory: ./app-recipes-nicaraguan
        # Wait for frontend to be ready on port 3000
      - name: Wait for Frontend
        run: wait-on http://localhost:3000

      - name: Run Playwright API Tests
        run: npx playwright test tests/api.spec.ts
        working-directory: ./recipes-suite-automation

      - name: Run Playwright UI Tests
        run: npx playwright test tests/recipes.spec.ts
        working-directory: ./recipes-suite-automation

      - name: Upload Playwright Test Report
        uses: actions/upload-artifact@v4
        if: always() # Always upload, even if tests fail
        with:
          name: playwright-report
          path: recipes-suite-automation/playwright-report/
          retention-days: 5
